Запись изменений в репозиторий.
htmlacademy-adaptive/2178613-cat-energy-27 pull request #2
Opened 2022-12-09 22:24 UTC by nikolai-skor

2022-12-12 19:11 UTC, nikolai-skor commented
Разметка

2022-12-13 07:45 UTC, mkolotovich requested changes

2022-12-13 07:45 UTC, mkolotovich commented on source/index.html
> +      <a class="logo__link logo-text" href="#">
логотип - это должна быть одна ссылка, а не две

2022-12-13 07:45 UTC, mkolotovich commented on source/index.html
> +    <div class="main-header__logo logo">
у нас есть критерий - https://up.htmlacademy.ru/adaptive/27/criteries#d2

2022-12-13 07:45 UTC, mkolotovich commented on source/index.html
> +      <div class="main-nav__wrapper">
у нас есть критерий - https://up.htmlacademy.ru/adaptive/27/criteries#d2

2022-12-13 07:45 UTC, mkolotovich commented on source/index.html
> +      <p class="promo__promo-desc promo-desc"></p>
пропущен текст - Занялся собой? Займись котом!

2022-12-13 07:45 UTC, mkolotovich commented on source/index.html
> +      <div class="promo__field"></div>
у нас есть критерий - https://up.htmlacademy.ru/adaptive/27/criteries#d2

2022-12-13 07:45 UTC, mkolotovich commented on source/index.html
> +      <div class="feature__wrap">
если блок содержит заголовок, то лучше оборачивать его в section

2022-12-13 07:45 UTC, mkolotovich commented on source/index.html
> +    <section class="main-container__feature feature">
если в блоке заголовка нет, то лучше обернуть его в div

2022-12-13 07:45 UTC, mkolotovich commented on source/index.html
> +          <dt class="advantages-list__advantages-icon advantages-icon">
тег dt используется для термина, а у вас в нем лежит изображение. Я думаю, что здесь лучше разметить список тегом ul вместо dl

2022-12-13 07:45 UTC, mkolotovich commented on source/index.html
> +    </section>
эта секция я считаю, что она избыточна. Её содержимое(список) перенесите внутрь предыдущей секции

2022-12-13 07:45 UTC, mkolotovich commented on source/index.html
> +    <span class="main-container__desc">Затраты на питание: 15 000 РУБ. </span>
этот тег тоже перенисите в предыдущюю секцию

2022-12-13 07:45 UTC, mkolotovich commented on source/index.html
> +    <section class="main-container__slider slider">
эта секция тоже избыточна. Ее можно разметить так: два изображения и кнопка

2022-12-13 07:45 UTC, mkolotovich commented on source/index.html
> +      <h2 class="visually-hidden">Мы находимся здесь.</h2>
добавьте карту

2022-12-13 07:45 UTC, mkolotovich commented on source/index.html
> +    <div class="main-footer__wrap">
у нас есть критерий - https://up.htmlacademy.ru/adaptive/27/criteries#d2

2022-12-13 07:45 UTC, mkolotovich commented on source/index.html
> +        </a>
здесь не логотип, а просто текст и он должен быть без ссылки

2022-12-13 07:45 UTC, mkolotovich commented on source/index.html
> +            <a class="site-list__link" href="#">
здесь должна быть ссылка на страницу catalog

2022-12-13 07:45 UTC, mkolotovich commented on source/catalog.html
> +  </header>
шапку разметьте как на главной

2022-12-13 07:45 UTC, mkolotovich commented on source/catalog.html
> +          </a>
предлагаю в элементах списка изменить порядок элементов, чтобы они соответствовали макету, т.е. вначале изображение, а потом название. Также у вас не соответствуют названия товаров и описание товаров макету и количество товаров

2022-12-13 07:45 UTC, mkolotovich commented on source/catalog.html
> +        </li>
не размечены еще 3 элемента списка

2022-12-13 07:45 UTC, mkolotovich commented on source/catalog.html
> +    </section>
эта секция избыточна, переместите её содержимое в предыдущюю секцию

2022-12-13 07:45 UTC, mkolotovich commented on source/catalog.html
> +
добавьте карту

2022-12-13 07:45 UTC, mkolotovich commented on source/catalog.html
> +  </footer>
разметьте подвал как на главной

2022-12-13 07:45 UTC, mkolotovich commented on source/catalog.html
> +              Подбор программы
добавьте ссылку на страницу form

2022-12-13 07:45 UTC, mkolotovich commented on source/form.html
> +  </header>
разметьте шапку как на главной

2022-12-13 07:45 UTC, mkolotovich commented on source/form.html
> +          совет)</label>
нарушен критерий - https://up.htmlacademy.ru/adaptive/27/criteries#b32

2022-12-13 07:45 UTC, mkolotovich commented on source/form.html
> +      <h2 class="visually-hidden">Мы находимся здесь.</h2>
добавьте карту

2022-12-13 07:45 UTC, mkolotovich commented on source/form.html
> +  </footer>
разметьте подвал как на главной

2022-12-16 03:16 UTC, nikolai-skor commented on source/catalog.html
> +          </a>
В списке название идет первым элементом, потому что это заголовок (вроде так семантичнее по мнению создателей курса). Рокировку можно организовать через CSS св-во order. Описасие просто размножил, ожидая возврат проекта на доработку.

2022-12-16 07:31 UTC, mkolotovich requested changes
исправьте один комментарий и я приму ваш ПР

2022-12-16 07:31 UTC, mkolotovich commented on source/catalog.html
>              </dd>
тут в макете другой вес

2022-12-16 09:24 UTC, merged