Добавляет сборку на SCSS.
htmlacademy-adaptive/2178613-cat-energy-27 pull request #3
Opened 2022-12-21 22:17 UTC by nikolai-skor

2022-12-29 11:50 UTC, kolotovich-mike requested changes
исправьте комментарии

2022-12-29 11:50 UTC, kolotovich-mike commented on source/sass/style.scss
> +@use "./components/logo-text.scss";
этих файлов не существует, из-за этого сборка падает

2022-12-29 11:50 UTC, kolotovich-mike commented on source/sass/style.scss
> +@use "./components/advantages-icon.scss";
этого файла не существует, из-за этого сборка падает

2022-12-29 11:50 UTC, kolotovich-mike commented on source/sass/style.scss
> +@use "./components/slider-button.scss";
этих файлов не существует, из-за этого сборка падает

2022-12-29 11:50 UTC, kolotovich-mike commented on source/sass/style.scss
> +@use "./components/social-groupe.scss";
этого файла не существует, из-за этого сборка падает

2022-12-29 11:50 UTC, kolotovich-mike commented on source/sass/style.scss
> +@use "./components/checkbox-window.scss";
этого файла не существует, из-за этого сборка падает

2022-12-29 11:50 UTC, kolotovich-mike commented on source/sass/style.scss
> +@use "./components/product-image.scss";
этих файлов не существует, из-за этого сборка падает

2022-12-29 11:50 UTC, kolotovich-mike commented on source/sass/style.scss
> +@use "./components/product-desc.scss";
этих файлов не существует, из-за этого сборка падает

2022-12-29 11:50 UTC, kolotovich-mike commented on source/sass/components/promo.scss
> +  background-color: rgba($color: #68b738, $alpha: 0.85);
в задании указано - задайте фоновые цвета и фоновые изображения для блоков; У вас указан только фоновый цвет

2022-12-29 11:50 UTC, kolotovich-mike commented on source/sass/components/main-footer.scss
> +  top: 39px;
зачем вы задаете позицию аблосют? эти правила лишние уберите их

2022-12-29 11:50 UTC, kolotovich-mike commented on source/form.html
>  <body class="page__body">
добавьте еще один класс например page__inner

2022-12-29 11:50 UTC, kolotovich-mike commented on source/sass/components/page.scss
> +
создайте селектор .page__inner .location и задайте ему background: #F2F2F2;

2022-12-29 11:50 UTC, kolotovich-mike commented on source/sass/components/button.scss
> +}
создайте селектор .button--secondary и задайте ему background: #F2F2F2; font-size: 16px;
line-height: 20px; color: #444444;

2022-12-29 11:50 UTC, kolotovich-mike commented on source/sass/components/gift.scss
> +  background-color: rgba($color: #68b738, $alpha: 0.85);
в задании указано - задайте фоновые цвета и фоновые изображения для блоков; У вас указан только фоновый цвет

2022-12-29 11:50 UTC, kolotovich-mike commented on source/catalog.html
>  <body class="page__body">
добавьте класс например .page__inner

2022-12-29 11:50 UTC, kolotovich-mike commented on source/sass/components/form-radiobutton.scss
> +}
создайте селектор .form-radiobutton__form-label и задайте ему color: #222222;

2022-12-29 11:50 UTC, kolotovich-mike commented on source/sass/global/fonts.scss
> +  src: url("../../fonts/oswald/oswaldmedium.woff2") format("woff2");
путь к файлам шрифтов должен быть вида src: url("../fonts/oswald/oswaldregular.woff2") format("woff2");

2022-12-29 11:50 UTC, kolotovich-mike commented on source/sass/components/form-checkbox.scss
> +}
создайте селектор .form-checkbox__form-label и задайте ему color: #000000;

2022-12-29 11:50 UTC, kolotovich-mike commented on source/sass/components/form.scss
> +  width: 100%;
задайте font-size: 16px;
line-height: 20px;

2022-12-29 11:50 UTC, kolotovich-mike commented on source/sass/components/form.scss
> +  text-align: center;
задайте line-height: 16px; color: #000000;

2022-12-29 11:50 UTC, kolotovich-mike commented on source/sass/components/product-item.scss
> +
создайте селектор .product-item .button и задайте ему font-size: 16px;
line-height: 20px;

2022-12-29 11:50 UTC, kolotovich-mike commented on source/sass/components/product-item.scss
> +}
создайте селектор .product-item__product-item-title и задайте ему color: #111111;

2022-12-29 11:50 UTC, kolotovich-mike commented on source/sass/components/form-legend.scss
> +  line-height: 26px;
измените значение на 24px

2022-12-29 11:50 UTC, kolotovich-mike commented on source/sass/components/product-additional-list.scss
> +}
создайте селектор .product-additional-item__product-item-title и задайте ему line-height: 16px;

2022-12-29 11:50 UTC, kolotovich-mike commented on source/sass/components/product-item.scss
> +}
создайте селектор .product-desc и задайте ему line-height: 14px;

2022-12-29 11:50 UTC, kolotovich-mike commented on source/sass/components/catalog-additional-products.scss
> +
создайте селектор .catalog-additional-products__product-additional-item .button и задайте ему font-size: 16px;
line-height: 20px;

2022-12-29 11:50 UTC, kolotovich-mike commented on source/sass/components/gift.scss
> +  line-height: 16px;
задайте font-size: 16px;
line-height: 20px;

2023-01-02 18:24 UTC, nikolai-skor commented on source/sass/style.scss
> +@use "./components/product-image.scss";
пару раз споткнулся о неподключенные блоки, поэтому подключил сразу все до момента, когда вскроются ненужные

2023-01-02 18:34 UTC, nikolai-skor commented on source/sass/global/fonts.scss
> +  src: url("../../fonts/oswald/oswaldmedium.woff2") format("woff2");
путь к шрифтам "source/fonts/...", а путь к файлу со шрифтами "source/sass/global/fonts.scss", вроде все работает

2023-01-03 03:21 UTC, nikolai-skor commented on source/sass/components/promo.scss
> +  background-color: rgba($color: #68b738, $alpha: 0.85);
пока не знаю, как будет реализована адаптация, поэтому временно оставляю фоновую картинку как есть

2023-01-03 04:25 UTC, nikolai-skor commented on source/sass/components/product-additional-list.scss
> +}
пользуясь возможностью препроцессоров, я сыграл модификатором .product-item-title--additional, вложенным на втором уровне правилом через &. надеюсь, что не нарушил критерии

2023-01-03 05:05 UTC, nikolai-skor commented on source/sass/components/page.scss
> +
снова реализовал через модификатор. если это недопустимо или нежелательно, то исправлю в случае критики с вашей стороны

2023-01-03 05:13 UTC, nikolai-skor commented on source/sass/components/main-footer.scss
> +  top: 39px;
убрал, отцентровал

2023-01-04 05:36 UTC, nikolai-skor commented on source/sass/components/form-legend.scss
> +  line-height: 26px;
тут значения вроде совпадают с макетом

2023-01-07 08:36 UTC, mkolotovich commented on source/sass/style.scss
> +@use "./components/product-desc.scss";
этого файла не существует, из-за этого сборка падает

2023-01-07 08:36 UTC, mkolotovich commented on source/sass/components/form-legend.scss
> +  line-height: 26px;
нет не совпадают, в макете 24px, а у вас указано 26px. Исправьте

2023-01-07 08:39 UTC, mkolotovich requested changes
исправьте не схлопнутые комментарии с прошлой проверки(к ним я оставил комментарии)

2023-01-09 09:11 UTC, merged